import { GoogleGenerativeAI } from "@google/generative-ai";

/**
 * Extracts structured data from raw transcript using Gemini.
 * Ensure GEMINI_API_KEY is configured in .env.
 */
export const extractStructuredTranscript = async (rawTranscript) => {
  try {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      console.warn("No Gemini API Key found, returning dummy structured transcript");
      return generateDummyStructuredData(rawTranscript);
    }
    
    const genAI = new GoogleGenerativeAI(apiKey);
    const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });

    const prompt = `You are a medical data extraction bot. 
Extract specific fields from the following conversation transcript:
- Chief_Complaint
- Symptom_Duration
- Pain_Scale_1_to_10
- Requested_Time

Transcript: "${rawTranscript}"

Return the output STRICTLY as raw JSON. Do not write markdown blocks (\`\`\`json). Just the JSON string.
`;

    const result = await model.generateContent(prompt);
    const response = await result.response;
    const text = response.text();
    
    // Clean up markdown in case the model ignored instructions
    const cleanJson = text.replace(/^```json|^```|```$/gm, "").trim();
    return JSON.parse(cleanJson);
  } catch (error) {
    console.error("LLM Extraction Error (Gemini):", error.message);
    return generateDummyStructuredData(rawTranscript);
  }
};

const generateDummyStructuredData = (transcript) => {
  // Fallback for demo without real API keys
  return {
    Chief_Complaint: "General issue detected in transcript",
    Symptom_Duration: "Unknown",
    Pain_Scale_1_to_10: 2,
    Requested_Time: null,
    Note: "Generated by fallback system. Please check API key."
  };
};